-- vim.keymap.set("n", "<Space>t", "<cmd>ToggleTerm<CR>", {
--     desc = "Toggle Terminal"
-- })
-- -- ターミナルモードでは独自の動作
-- vim.keymap.set("t", "jj", [[<C-\><C-n><cmd>ToggleTerm<CR>]], {
--     desc = "Toggle terminal (from terminal mode)"
-- })
-- vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]], {
--     desc = "Exit terminal mode"
-- })
