[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

# [[plugins]]
# repo = 'roxma/nvim-completion-manager'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'yuratomo/w3m.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['neosnippet.vim']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = ['vimproc.vim']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']

[[plugins]]
repo = 'chrisbra/csv.vim'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
