[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python','int-python']
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python','int-python']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c','cpp','objective-c']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'
